### ISSUE TITLE
KT CENTRAL HOMEPAGE - Styling in newsfeed section

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/kitchentable#1]
Need to clean up spacing and styling in the news feed section of the homepage.

**Comment by jakewelchert** [comment]
@colinandjessica This is available for review so please take a look when you can.

**Comment by colinandjessica** [comment]
seems a little crowded at the bottom of the section. Maybe a little more space before the dough/hand picture

**Comment by jakewelchert** [comment]
Good catch. Updated.
