### ISSUE TITLE
happy hour on dt - again get it you said no photos

### ISSUE THREAD

**Issue by colinandjessica** [jakewelchert/kitchentable#10]
But we need a photo of something that is actually a part of the happy hour menu pls

**Comment by jakewelchert** [comment]
Sorry, but I'm confused. Are you saying there needs to be a Happy Hour button on the downtown menu, or you want a Happy Hour section on the downtown homepage?

**Comment by colinandjessica** [comment]
Buttons are fine, just want a different picture but like you said, can be addressed later.
