### ISSUE TITLE
menu buttons - both dt and ct

### ISSUE THREAD

**Issue by colinandjessica** [jakewelchert/kitchentable#11]
Thoughts on a button shaped like the order pick-up/delivery buttons at the bottom, more a rounded rectangle than a text msg blurb??

**Comment by jakewelchert** [comment]
I would like to avoid all of the repitition of the other buttons. I can try using a similar shape, but will keep them grey.

**Comment by jakewelchert** [comment]
Resolved. Buttons are changed to the same shape as the others. Background turns grey on hover.
