### ISSUE TITLE
Downtown landing page

### ISSUE THREAD

**Issue by colinandjessica** [jakewelchert/kitchentable#17]
Seems to be a lot of extra space above and below the picture slider

Buttons for online ordering both say order pickup, one should say order delivery

Not sure about the giant arrows in the private party section at the bottom of the page. Maybe something a little more subtle to indicate picture scrolling.

**Comment by jakewelchert** [comment]
@colinandjessica Can you try refreshing to get rid of those giant arrows? Or, can you take a screenshot of those so I know how they look on your end?

**Comment by jakewelchert** [comment]
@colinandjessica I'm not seeing these anymore on my end. Can you try hard refreshing your page a few times? ---- Command + Shift + R
