### ISSUE TITLE
our story page

### ISSUE THREAD

**Issue by colinandjessica** [jakewelchert/kitchentable#19]
Arrows again

**Comment by colinandjessica** [comment]
![screenshot 2017-08-24 15 47 46](https://user-images.githubusercontent.com/31226791/29688111-2b66ecda-88e4-11e7-99b7-d7465f5d3c60.png)
![screenshot 2017-08-24 15 48 17](https://user-images.githubusercontent.com/31226791/29688112-2b683d4c-88e4-11e7-8a19-6897fb204331.png)
![screenshot 2017-08-24 15 48 59](https://user-images.githubusercontent.com/31226791/29688110-2b66559a-88e4-11e7-9368-b9c0de4a55a4.png)

**Comment by jakewelchert** [comment]
@colinandjessica Yeah, those aren't supposed to be like that! Probably a browser issue that is easily fixed. What browser are you looking at this on?

**Comment by colinandjessica** [comment]
chrome

**Comment by jakewelchert** [comment]
@colinandjessica I'm not seeing these anymore on my end. Can you try hard refreshing your page a few times? ---- Command + Shift + R

If you're still getting it I can try another approach. Things should look like this...

<img width="712" alt="screen shot 2017-08-24 at 9 24 20 pm" src="https://user-images.githubusercontent.com/3301072/29697085-a76ac238-8912-11e7-9875-66365e1492fe.png">
