### ISSUE TITLE
central menu page

### ISSUE THREAD

**Issue by colinandjessica** [jakewelchert/kitchentable#23]
Footer is not updated on the right hand side

**Comment by colinandjessica** [comment]
When you click on menu in the header the three tabs in the footer are correct, but when you click through the individual menu tabs the three tabs in the footer change. The orange arrow is not there and the font is much larger.

**Comment by jakewelchert** [comment]
@colinandjessica Great catch! This was a template issue that is now resolved. You may need to refresh to see the change.
