### ISSUE TITLE
view full menu tab on each sites landing

### ISSUE THREAD

**Issue by colinandjessica** [jakewelchert/kitchentable#7]
Can the view full menu button move to below the top slider - or all three, what do you think would be best balance and best presented?

**Comment by jakewelchert** [comment]
@colinandjessica I've made this change to the downtown homepage: http://kitchentable.flywheelsites.com/downtown/

To me, it feels like it doesn't make sense here. We already have all of these in the navigation, and the Today's Specials is an information block that we want people to read and then decide if they want to Order or view full menu. Doesn that make sense? Let me know what you think.

**Comment by colinandjessica** [comment]
What do you think about a view all day menu tab above todays specials and the order pickup and order delivery tabs below?

**Comment by jakewelchert** [comment]
This looks a little strange, so we can just keep them all at the top. See image.

![screen shot 2017-08-29 at 9 22 44 am](https://user-images.githubusercontent.com/3301072/29826479-08170e6a-8c9d-11e7-9313-c2e1729b405a.png)

**Comment by colinandjessica** [comment]
Let's go with all three at the top.

**Comment by jakewelchert** [comment]
Great! Resolved.
