### ISSUE TITLE
sliders - both landing pages

### ISSUE THREAD

**Issue by colinandjessica** [jakewelchert/kitchentable#8]
Know you said you don't want to discus pictures, but before we forget and a picture we don't like keeps appearing, wanted to get it out there - the fan behind the bar, though necessary for humidity, should have been removed before the shot...

**Comment by jakewelchert** [comment]
@colinandjessica Okay, this can be fixed but is low priority since it's an image.

**Comment by colinandjessica** [comment]
Not certain what the giant arrows are for?

**Comment by jakewelchert** [comment]
@colinandjessica Sorry about this! Can you try refreshing your browser a few times?

**Comment by jakewelchert** [comment]
Moved to another issue.
